//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeduShop.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTag
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string TagID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual Tag Tag1 { get; set; }
    }
}
